map_update_interval: 2.0  # how long to update map (5.0)
maxUrange: 120.0  # max usable range of laser. Set less than sensor range
maxRange: 131.0  # set greater than sensor actual range
sigma: 0.05
kernelSize: 1
lstep: 0.05
astep: 0.05
iterations: 5
lsigma: 0.075
ogain: 3.0
lskip: 0
minimumScore: 25 # set higher if estimates seems jumpy in open spaces 
srr: 0.1
srt: 0.2
str: 0.1
stt: 0.2
linearUpdate: 2.0
angularUpdate: 0.9
temporalUpdate: 0.5
resampleThreshold: 0.5
particles: 100 # number of particles in filter (30)
xmin: -10.0
ymin: -10.0
xmax: 10.0
ymax: 10.0
delta: 0.75
llsamplerange: 0.01
llsamplestep: 0.01
lasamplerange: 0.005
lasamplestep: 0.005
